version: 1.0.{build}
build:
  verbosity: detailed
environment:
  password:
    secure: LiN40OzJiktb2MI8lxOGE5RUKLhhDR//OoIztwNhi64=
  github_token:
    secure: Yp8Hru/6BZNwRDNWB1p/E+kLxsLsoCNpCO5dojhX4GgaozmZz59a6ugWF3W/6lgQ
#init:
#- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
install:
#- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-desktop.ps1'))
- AppVeyorInstall.bat
build_script:
- AppVeyorBuild.bat

