version: 1.0.{build}
skip_non_tags: true
build:
  verbosity: detailed
environment:
  matrix:
  - what: maintenance
    github_token:
      secure: qFyROGp9we0D/CfiUCzEur8uIxnRiuZnFV+qCwWSqe+EZAdQwGGhZp23+Dko+mcx
    password:
      secure: H1HXpTD6gugn7P9+cS/CpvvgilpIV5c9gXdgW7QU+c+Af/wwHqJoKqWB5y6RNk/B
  - what: test-packages
    password:
      secure: arvBMKlrMziJ1FuFLBserjuPMaoRFotnP0taHpcR5JI=
    virustotal_key:
      secure: aNItImrmTcvg9A+nbuTAZvN9FFPYiEy54qenOsBBlzCHxpgVAyEv72bcnEoTBvS1F6uPaesSxLf1G4+c0UzPoqAQC9T3J+o/UHxooEuhEHI=
#init:
#- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
install:
#- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-desktop.ps1'))
- AppVeyorInstall.bat
build_script:
- AppVeyorBuild.bat

