version: 1.0.{build}
skip_non_tags: true
build:
  verbosity: detailed
environment:
  password:
    secure: LiN40OzJiktb2MI8lxOGE5RUKLhhDR//OoIztwNhi64=
  github_token:
    secure: TtoutOpS9sW/0d6en/6TaCLmAnZEeM3C1C6xBFb63UaTiY8exT4y3i4GSS3QK7nT
#init:
#- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
install:
#- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-desktop.ps1'))
- AppVeyorInstall.bat
build_script:
- AppVeyorBuild.bat

