version: 1.0.{build}
skip_non_tags: true
build:
  verbosity: detailed
environment:
  matrix:
  - what: download-repositories
  - what: test-packages
  password:
    secure: LiN40OzJiktb2MI8lxOGE5RUKLhhDR//OoIztwNhi64=
  github_token:
    secure: TtoutOpS9sW/0d6en/6TaCLmAnZEeM3C1C6xBFb63UaTiY8exT4y3i4GSS3QK7nT
  virustotal_key:
    secure: aNItImrmTcvg9A+nbuTAZvN9FFPYiEy54qenOsBBlzCHxpgVAyEv72bcnEoTBvS1F6uPaesSxLf1G4+c0UzPoqAQC9T3J+o/UHxooEuhEHI=
#init:
#- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
install:
#- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-desktop.ps1'))
- AppVeyorInstall.bat
build_script:
- AppVeyorBuild.bat

